# Generated by Django 4.1 on 2022-11-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='kino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filmapp.kino'),
        ),
    ]
